version: "3.1"
nlu:
- intent: ask_comission_pricing
  examples: |
    - do I have to pay extra to buy stocks?
    - how much of a cut do you take?
    - does buying stock cost something?
    - how much order fee do you have?
    - if I place an order does that cost money?
    - how much does an order take?
    - is there an order fee to buy stocks?
    - how much to place an order?
    - is there an order fee?
    - what's the transaction cost?
    - what's the order fee?
    - do I have to pay you to buy or sell stock?
    - is there a fee?
    - how much do you charge per order?
    - is there a charge when I buy some stocks?
    - Will there be any additional costs for buying stocks?
- intent: buy_stock
  examples: |
    - can I buy some stocks?
    - I want to buy some securities.
    - buy [GOOG](ticker)
    - Buy [10](quantity) shares of [NFLX](ticker)
    - I want to invest in [TSLA](ticker)
    - can you help me invest in [GOOG](ticker)
    - I want to acquire [50](quantity) shares of [F](ticker).
    - I'd like to acquire [100](quantity) shares of [SHOP](ticker)
    - I got some dry powder and I want to use it for buying some stocks.
    - please place a limit order at [78.20](amount-of-money)$ to buy [50](quantity) shares of [GE](ticker)
    - I heard [AAPL](ticker) is about to bounce, I want to buy some
    - I'd like to buy some stocks again
- intent: do_investment
  examples: |
    - I want to know more investment options.
    - I have some money to invest.
    - Give me investment plans.
    - I want to invest.
    - I want to invest my money.
    - I want to invest my money in [stocks](investment_type).
    - I want to invest my money in [bonds](investment_type).
    - I want to invest my money in [mutual funds](investment_type).
    - I want to invest my money in [ETFs](investment_type).
    - I want to invest my money in [futures](investment_type).
    - I want to invest my money in [commodities](investment_type).
    - I want to invest my money in [real estate](investment_type).
    - I want to invest my money in [cryptocurrency](investment_type).
    - I want to invest my money in [gold](investment_type).
    - Show me investment options.
    - Show me investment plans.
    - Show me investment plans for [stocks](investment_type).
    - Show me investment plans for [bonds](investment_type).
    - Show me investment plans for [mutual funds](investment_type).
    - Show me investment plans for [ETFs](investment_type).
    - Show me investment plans for [futures](investment_type).
    - Show me investment plans for [commodities](investment_type).
    - Show me investment plans for [real estate](investment_type).
    - Show me investment plans for [cryptocurrency](investment_type).
    - Show me investment plans for [gold](investment_type).
    - I want to know more about investment options.
    - I want to know more about investment plans.
    - I want to know more about investment plans for [stocks](investment_type).
    - I want to know more about investment plans for [bonds](investment_type).
    - I want to know more about investment plans for [mutual funds](investment_type).
    - I want to know more about investment plans for [ETFs](investment_type).
    - I want to know more about investment plans for [futures](investment_type).
    - I want to know more about investment plans for [commodities](investment_type).
    - I want to know more about investment plans for [real estate](investment_type).
    - I want to know more about investment plans for [cryptocurrency](investment_type).
    - I want to know more about investment plans for [gold](investment_type).
- intent: financial_status
  examples: |
    - My name is [David](name). show my status?
    - My name is [Charlie](name). show my financial status?
    - My name is [Peter](name). what is my current financial status?

rules:
- rule: Ask comission pricing
  steps:
  - intent: ask_comission_pricing
  - action: utter_ask_comission_pricing

- rule: Buy some stocks
  steps:
  - intent: buy_stock
  - action: action_do_investment

- rule: Search for investment options
  steps:
  - intent: do_investment
  - action: action_do_investment

- rule: Show financial status
  steps:
  - intent: financial_status
  - action: action_show_status