recipe: default.v1
language: en
spaces:
- name: main
  domain: main/domain.yml
  stories: main/nlu/training_data.yml
  nlu: main/nlu/training_data.yml
  nlu_test: main/nlu/test_data.yml
- name: investment
  domain: investment/domain.yml
  stories: investment/nlu/training_data.yml
  nlu: investment/nlu/training_data.yml
  nlu_test: investment/nlu/test_data.yml
  entry_intents:
  - buy_stock
importers:
- name: rasa_plus.spaces.space_data_importer.SpaceDataImporter
  temporary_working_directory: spaces
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: rasa_plus.spaces.components.spaces_crf_entity_extractor.SpacesCRFEntityExtractor
- name: DIETClassifier
  epochs: 100
  ranking_length: 0
  entity_recognition: false
  BILOU_flag: false
- name: rasa_plus.spaces.components.filter_and_rerank.FilterAndRerank
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
policies: null
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
assistant_id: 20230317-032933-unsorted-game
