version: "3.1"
nlu:
- intent: greet
  examples: |
    - hey
    - hello
    - hi
    - good morning
    - good evening
    - hey there
    - good day
- intent: bot_challenge
  examples: |
    - you talk like a bot
    - are you a machine?
    - you are a bot, aren't you?
    - am I just talking to a machine?
    - am I talking to a bot?
    - you talk like a machine
    - am I talking to a human?
    - am I talking to a person?
    - you sound a lot like a bot
    - are you a virtual assistant or a person?
    - are you a human?
    - can you tell me whether I am talking to a person?

rules:
- rule: Greet user
  steps:
  - intent: greet
  - action: action_demo_greet
- rule: Check if bot
  steps:
  - intent: bot_challenge
  - action: utter_iamabot
