version: "3.1"
nlu:
- intent: pay_cc
  examples: |
    - Pay my [discover](credit_card)
    - pay off my credit card
    - I want to pay my credit card
    - I want to pay the [current balance](amount-of-money-description) on my credit card
    - i want to pay my credit card
    - Pay off my credit card, please
    - I want to pay my card
    - I want to pay my [MasterCard](credit_card) bill
    - I want to pay my [Master Card](credit_card) bill
    - I want to pay my [MC](credit_card) bill
    - I guess it is. Since it's so much, let's pay off my credit
    - I want to pay $ [500](amount-of-money) on my [emblem](credit_card) credit card on Sunday
    - Please schedule  a payment towards my credit card for April 12th
    - I would like to pay the [minimum balance](amount-of-money-description) on my [emblem](credit_card) card
    - Pay off my [minimum balance](amount-of-money-description) please
    - i want to pay my [current balance](amount-of-money-description) on my [emblem](credit_card) credit card
    - I want to pay my [current balance](amount-of-money-description) on my [emblem](credit_card) credit card today
    - id like to pay my bill
    - Pay my card
    - I want to pay my credit card bill
    - i want to pay off my [emblem](credit_card) credit card
    - Can I schedule a payment towards my credit card for tomorrow?
    - i need to pay off my [emblm](credit_card) credit card
    - I want to pay my [iron bank](credit_card) bill
    - I want to pay my [ironbank](credit_card) bill
    - I want to pay my [Ibank](credit_card) bill
    - I want to pay my [IB](credit_card) bill
    - pay a bill
    - i want to pay off my credit card
    - I want to pay [100](amount-of-money) dollars toward my [Emblem](credit_card) card, tomorrow
    - could I pay off my credit card?
    - Pay my [visa](credit_card)
    - can you help me pay the [current balance](amount-of-money-description) on my credit card
    - pay [100](amount-of-money) USD towards [emblem](credit_card) card, tomorrow
    - Pay my [mastercard](credit_card)
    - I want to pay my [visa](credit_card) bill
- intent: inform
  examples: |
    - [emblem](credit_card) credit card
    - a [hundred dollars](amount-of-money)
    - my [emblem](credit_card) card
    - I want to pay the [current balance](amount-of-money-description)
    - [current balance](amount-of-money-description)
    - $ [10](amount-of-money)
    - [visa](credit_card)
    - [1000](amount-of-money) dollars
    - [justice bank](credit_card)
    - [100](amount-of-money) dollars
    - [iron bank](credit_card)
    - [emblem](credit_card)
    - towards my [justice bank](credit_card) card
    - $ [500](amount-of-money)
    - the [minimum balance](amount-of-money-description)
    - [Gringos](credit_card)
    - My [chase](credit_card)
    - [emblem](credit_card) card
    - [iron bank](credit_card) card
    - [justice bank](credit_card) card
    - [5000](amount-of-money)
    - [Iron Bank](credit_card)
    - [iron bank](credit_card) account
    - in [full](amount-of-money-description)
    - my [justice bank](credit_card) card
    - [iron bank](credit_card) credit card
    - my [justice bank](credit_card) credit card
    - the [full balance](amount-of-money-description)
    - My [visa](credit_card)
    - my [minimum balance](amount-of-money-description)
    - [emblem](credit_card) account
    - [minimum balance](amount-of-money-description)
    - towards my [emblem](credit_card) card
    - $ [100](amount-of-money)
    - my [rasa](credit_card) account
    - $ [500](amount-of-money)
    - My [Visa](credit_card) account
    - towards my [iron bank](credit_card) card
    - my [current balance](amount-of-money-description)

- synonym: mastercard
  examples: |
    - master card
    - MC

- synonym: ironbank
  examples: |
    - iron bank
    - IBank
    - IB
